FROM python:3-slim

ENV APP_USER user
ENV APP_ROOT /opt/b2b_test/

# Celery рекомендуется запускать от обычного пользователя
RUN groupadd -r ${APP_USER} \
    && useradd -r -m \
    --home-dir ${APP_ROOT} \
    -s /usr/sbin/nologin \
    -g ${APP_USER} ${APP_USER}

ADD requirements.txt .
RUN pip install -r requirements.txt

WORKDIR ${APP_ROOT}

USER ${APP_USER}
