# Generated by Django 2.1 on 2018-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('url', models.URLField(verbose_name='URL')),
                ('date', models.DateField(verbose_name='дата загрузки')),
                ('key_words', models.ManyToManyField(related_name='videos', to='yt_search_api.SearchKeyword', verbose_name='ключевые слова')),
            ],
        ),
    ]
