# Generated by Django 2.1 on 2018-09-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search_api', '0002_ytvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchkeyword',
            name='word',
            field=models.CharField(max_length=255, unique=True, verbose_name='слово'),
        ),
    ]
