# Generated by Django 2.1 on 2018-09-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search_api', '0003_auto_20180921_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchkeyword',
            old_name='word',
            new_name='key_word',
        ),
    ]
