# Generated by Django 2.1 on 2018-09-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search_api', '0004_auto_20180921_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideo',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='дата загрузки'),
        ),
    ]
