# Generated by Django 2.1 on 2018-09-26 00:48

from datetime import datetime

from django.db import migrations
from django.utils import timezone


def transfer_date(apps, schema_editor):
    YTVideo = apps.get_model('yt_search_api', 'YTVideo')

    for video in YTVideo.objects.filter(published_at__isnull=True):
        UTC_tz = timezone.pytz.timezone('UTC')
        datetime_from_date = datetime.combine(video.date, datetime.min.time())

        video.published_at = timezone.make_aware(datetime_from_date, timezone=UTC_tz)
        video.save()


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search_api', '0005_ytvideo_published_at'),
    ]

    operations = [
        migrations.RunPython(transfer_date),
    ]
