# Generated by Django 2.1 on 2018-09-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search_api', '0006_transfer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytvideo',
            name='date',
        ),
    ]
