# Generated by Django 2.1 on 2018-09-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search_api', '0007_remove_ytvideo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideo',
            name='published_at',
            field=models.DateTimeField(verbose_name='дата загрузки'),
        ),
    ]
